//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXWebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AUX_REMISIONES
    {
        public AUX_REMISIONES()
        {
            this.HT_DOCUMENTOS = new HashSet<HT_DOCUMENTOS>();
        }
    
        public int PK_REMISIONES { get; set; }
        public string CLAVE_DOC { get; set; }
        public string DISPONIBLE { get; set; }
        public string CEDIS { get; set; }
        public string TIPO { get; set; }
        public Nullable<int> FK_EMPRESA { get; set; }
    
        public virtual ICollection<HT_DOCUMENTOS> HT_DOCUMENTOS { get; set; }
        public virtual CAT_EMPRESA CAT_EMPRESA { get; set; }
    }
}
