//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXWebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAT_TARIFA
    {
        public string CEDIS { get; set; }
        public string DESTINO { get; set; }
        public string PROVEEDOR { get; set; }
        public string TRANSPORTE { get; set; }
        public Nullable<double> TARIFA { get; set; }
        public int PK_TARIFA { get; set; }
    }
}
