//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXWebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAT_EMPRESA
    {
        public CAT_EMPRESA()
        {
            this.AUX_REMISIONES = new HashSet<AUX_REMISIONES>();
        }
    
        public int PK_EMPRESA { get; set; }
        public string NOMBRE { get; set; }
    
        public virtual ICollection<AUX_REMISIONES> AUX_REMISIONES { get; set; }
    }
}
