//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXWebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HT_DOCUMENTOS
    {
        public int PK_HT_DOCUMENTOS { get; set; }
        public Nullable<int> FK_EMBARQUE_HT { get; set; }
        public string FOLIO_EMBARQUE { get; set; }
        public string TIPO_DOCUMENTO { get; set; }
        public string CLAVE_DOCUMENTO { get; set; }
        public string TOTAL_PARCIAL { get; set; }
        public string PROCESADO { get; set; }
        public Nullable<int> FK_REMISIONES { get; set; }
    
        public virtual UE_EMBARQUEHT UE_EMBARQUEHT { get; set; }
        public virtual AUX_REMISIONES AUX_REMISIONES { get; set; }
    }
}
