//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXWebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HT_SUBDESTINOS
    {
        public int PK_SUBDESTINO { get; set; }
        public Nullable<int> FK_HT_DETALLE { get; set; }
        public string FOLIO_EMBARQUE { get; set; }
        public string CLAVE_DOCUMENTO { get; set; }
        public string DIRECCION_ENTREGA { get; set; }
        public string CLAVE_PEDIDO { get; set; }
        public string CLAVE_ORDEN_COMPRA { get; set; }
        public string CLAVE_CLIENTE { get; set; }
        public string CLAVE_ARTICULO { get; set; }
        public Nullable<double> CANTIDAD_EMBARCADA { get; set; }
        public Nullable<double> SUBD_1 { get; set; }
        public Nullable<double> SUBD_2 { get; set; }
        public Nullable<double> SUBD_3 { get; set; }
        public Nullable<double> SUBD_4 { get; set; }
        public Nullable<double> SUBD_5 { get; set; }
        public Nullable<double> SUBD_6 { get; set; }
        public Nullable<double> SUBD_7 { get; set; }
        public Nullable<double> SUBD_8 { get; set; }
        public Nullable<double> SUBD_9 { get; set; }
        public Nullable<double> SUBD_10 { get; set; }
    
        public virtual SIS_HT_DETALLE SIS_HT_DETALLE { get; set; }
    }
}
