//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXWebApplication1.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EMBARQUESRHEEMEntities : DbContext
    {
        public EMBARQUESRHEEMEntities()
            : base("name=EMBARQUESRHEEMEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CAT_CEDIS> CAT_CEDIS { get; set; }
        public virtual DbSet<CAT_DESTINO> CAT_DESTINO { get; set; }
        public virtual DbSet<CAT_PROVEEDOR> CAT_PROVEEDOR { get; set; }
        public virtual DbSet<CAT_PROVIENE_DE> CAT_PROVIENE_DE { get; set; }
        public virtual DbSet<CAT_STATUS_EMBARQUE> CAT_STATUS_EMBARQUE { get; set; }
        public virtual DbSet<CAT_STATUS_RETORNO> CAT_STATUS_RETORNO { get; set; }
        public virtual DbSet<CAT_TIPO_DEVOLUCION> CAT_TIPO_DEVOLUCION { get; set; }
        public virtual DbSet<CAT_TIPO_EMBARQUE> CAT_TIPO_EMBARQUE { get; set; }
        public virtual DbSet<CAT_TIPO_HT> CAT_TIPO_HT { get; set; }
        public virtual DbSet<CAT_TRANSPORTE> CAT_TRANSPORTE { get; set; }
        public virtual DbSet<HT_DOCUMENTOS> HT_DOCUMENTOS { get; set; }
        public virtual DbSet<AUX_FOLIOS> AUX_FOLIOS { get; set; }
        public virtual DbSet<SIS_HT_DETALLE> SIS_HT_DETALLE { get; set; }
        public virtual DbSet<UE_EMBARQUEHT> UE_EMBARQUEHT { get; set; }
        public virtual DbSet<CAT_TARIFA> CAT_TARIFA { get; set; }
        public virtual DbSet<CAT_TIPO_ENTREGA> CAT_TIPO_ENTREGA { get; set; }
        public virtual DbSet<HT_SUBDESTINOS> HT_SUBDESTINOS { get; set; }
        public virtual DbSet<AUX_HT_SUBDESTINOS> AUX_HT_SUBDESTINOS { get; set; }
        public virtual DbSet<T_COI_POL> T_COI_POL { get; set; }
        public virtual DbSet<T_COI_POL_TMP> T_COI_POL_TMP { get; set; }
        public virtual DbSet<AUX_REMISIONES> AUX_REMISIONES { get; set; }
        public virtual DbSet<CAT_EMPRESA> CAT_EMPRESA { get; set; }
    }
}
