//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DXWebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_COI_POL
    {
        public string RDM { get; set; }
        public string C2031 { get; set; }
        public string FECHA { get; set; }
        public string MONEDA { get; set; }
        public string ESP_1 { get; set; }
        public string CR_DR { get; set; }
        public string DESCR_ESP { get; set; }
        public string C556 { get; set; }
        public string CTA_1 { get; set; }
        public string CTA_2 { get; set; }
        public string CTA_3 { get; set; }
        public string CTA_4 { get; set; }
        public string CERO_1 { get; set; }
        public string CERO_2 { get; set; }
        public string CERO_3 { get; set; }
        public string CERO_4 { get; set; }
        public string MONTO_DR1 { get; set; }
        public string MONTO_CR1 { get; set; }
        public string MONTO_DR2 { get; set; }
        public string MONTO_CR2 { get; set; }
        public string CBF1 { get; set; }
        public string CBF2 { get; set; }
        public string CBF3 { get; set; }
        public string CBF4 { get; set; }
        public string CBF5 { get; set; }
        public string CBF6 { get; set; }
        public string CBF7 { get; set; }
        public string CBF8 { get; set; }
        public string CBF9 { get; set; }
        public string CBF10 { get; set; }
        public string CBF11 { get; set; }
        public string CBF12 { get; set; }
        public string CBF13 { get; set; }
        public string CBF14 { get; set; }
        public string CBF15 { get; set; }
        public string CBF16 { get; set; }
        public string CBF17 { get; set; }
        public string CBF18 { get; set; }
        public Nullable<int> AÑO { get; set; }
        public Nullable<int> MES { get; set; }
    }
}
